name: telegram message
on: [pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_BOT_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ${{ github.actor }} created pr:
            Pull Request Title: ${{ github.event.pull_request.title }}

            Repository: ${{ github.repository }}

            See changes: https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}
